# Site settings
title: Hi, I'm Chloe Posthuma-Coelho!
author:
  name: Chloe Posthuma-Coelho
  email: chloeposthumacoelho@gmail.com.com
description: "My website."

# Build settings
remote_theme: jekyll/minima
